### ISSUE TITLE
Lock screen still auto locks while exploring views

### ISSUE THREAD

**Issue by dcallen7** [DGh0st/FLEXall#1]
As the title says. I’m not sure if there is some setting to enable, but the depiction on Zebra implies that it happens automatically

**Comment by DGh0st** [comment]
There are indeed no options, and it should stay alive as long as you are actively exploring views. Actively means interacting with it, just having it open without interactions (touches) does not/will not keep the screen on.
If you are actively exploring views and it locks then I am going to need more information (reproduction steps, etc).
If you want it to stay alive regardless of active-ness then that is not currently supported but pull requests are welcome (as long as they completely break existing functionality).

**Comment by DGh0st** [comment]
Revision [fae34f6](https://github.com/DGh0st/FLEXall/commit/fae34f67e42ac88d114e8ee9c11a9da4790579b6) should make it stay alive as long as the FLEX bar is on screen.

FLEXall 0.0.1-13 has this change as well.
