### ISSUE TITLE
Causes lockscreen to hang for several seconds after every sbreload.

### ISSUE THREAD

**Issue by KritantaDev** [DGh0st/FLEXall#3]
Removed every tweak from my phone except for this one, issue remained. Issue persists across all devices tested upon.

**How to replicate:**
1. Install this tweak
2. sbreload

**Comment by DGh0st** [comment]
Hm, not seeing it on either of the devices I have (iPhone 6+ iOS 12.4.3 and iPad 6 iOS 13.4.1, both on Checkra1n).

What version of libFLEX are you using?
What jailbreak are you using? lets hope this isn't jailbreak specific.

Code wise there isn't much that is run during bootup/respring/sbreload. There is a bunch of gesture creation but none of that should be blocking the main thread.
My guess for pre-libFLEX 4.0 would be [`-[FLEXObjectExplorerViewController possibleExplorerSections]`](https://github.com/DGh0st/FLEXall/blob/master/Tweak.xm#L174) hook but thats not something that should hang for long if at all.
Rest of the hooks are manage objects on the same thread without blocking so I am not seeing anything that could cause this.

**Comment by KritantaDev** [comment]
I've noticed it on both of my phones, with every Flex tweak i could find. 13.3 and 13.4, both X w/ Checkra1n.

I wonder if it could have anything to do with libflex itself or something large being loaded into it. 

With **only** libFlex/FlexAll installed, it hangs for about 4-5 seconds. 

With FlexAll _and_ Flexy (my crap fork) installed, it hangs for about 9-10 seconds. the long hang is likely due to the symbol collision issues, as oslog gets filled with info about it.

With only Flexy (my fork, classes bundled) installed, it hangs for 2-3 seconds. 

With nothing installed, the sbreload is instantly responsive.

**Comment by DGh0st** [comment]
As discussed on discord, made libFLEX only load on first gesture recognition in the late-loading branch. As I wasn't seeing the original issue, going to rely on you to verify whether that fixes it or not.

**Comment by KritantaDev** [comment]
Issue resolved with commit f350715 in branch late-loading
